image: condaforge/mambaforge
stages:
  - test
  - build
  - deploy

.before_script_tests:
  before_script:
    - apt-get update
    - apt-get -y install build-essential

    # Install SSH agent if not already installed
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'

    # Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)

    # Give the right permissions, otherwise ssh-add will refuse to add files
    # Add the SSH key stored in SSH_PRIVATE_KEY file type CI/CD variable to the agent store
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    
    # Create the SSH directory and give it the right permissions
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    # Add GitHub to the known hosts
    - ssh-keyscan -H github.com >> ~/.ssh/known_hosts

    # Set the git username and email
    - git config --global user.email "george.holt@stfc.ac.uk"
    - git config --global user.name "George Holt"

    # Install the conda environment
    - export PIP_CACHE_DIR="/opt/cache/pip"
    - source activate  
    - conda create -n freegsnke python=3.10
    - conda activate freegsnke

    # Install the package
    - pip install -e .[dev,freegs4e]

Core tests:
  stage: test
  only:
    - main
    - development
    - merge_requests
  extends: .before_script_tests
  script:
    # TESTS
    - python -m pytest -v
    # Formatting
    - black --check freegsnke/
    - isort --check --diff freegsnke/
    # DOCUMENTATION
    - cd docs/
    - pip install -r requirements_docs.txt
    - bash build_documentation.sh
  artifacts:
    paths:
      - docs/_build/html
    expire_in: 1 hour

Notebook tests:
  stage: test
  extends: .before_script_tests
  script:
    # EXAMPLES
    - jupyter nbconvert --execute --to notebook --inplace examples/machine_config.ipynb
    - jupyter nbconvert --execute --to notebook --inplace examples/basic_dynamical_evolution.ipynb
    - jupyter nbconvert --execute --to notebook --inplace examples/equilibrium_examples.ipynb
    - jupyter nbconvert --execute --to notebook --inplace examples/example_nonlinear_evolution_diverted.ipynb
    - jupyter nbconvert --execute --to notebook --inplace examples/example_nonlinear_evolution_limiter.ipynb
  rules:
    # Only run when pushing or merging to main
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
      when: always
    - when: never

Deploy docs STFC cloud:
  image: kroniak/ssh-client
  dependencies:
    - "Core tests"
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - echo "$ID_RSA_FREEGSNKE" | base64 -d > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh    
    - chmod 600 ~/.ssh/id_rsa    
    - eval "$(ssh-agent -s)"    
    - ssh-add ~/.ssh/id_rsa
  script:    
    - scp -o StrictHostKeyChecking=no -Cr docs/_build/html $STFC_CLOUD_USERNAME@172.16.110.116:./
  artifacts:
    expose_as: "docs_html"
    paths:
      - docs/_build/html/
    expire_in: never

  only:
    - main
    - development